# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Poke',
        ),
    ]
