# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_auto_20170928_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poke',
            old_name='recieve',
            new_name='receive',
        ),
    ]
