# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relationship',
            field=models.ManyToManyField(related_name='_user_relationship_+', to='main.User'),
        ),
    ]
