# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend',
            field=models.ManyToManyField(related_name='_user_friend_+', to='main.User'),
        ),
    ]
