# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='myLikes', to='main.User'),
        ),
    ]
